### ISSUE TITLE
Yet Another Cloud Notepad

### ISSUE THREAD

**Issue by tszlznl** [zhuima/awesome-cloudflare#10]
## [Serverless Cloud Notepad](https://github.com/s0urcelab/serverless-cloud-notepad)

地址：https://github.com/s0urcelab/serverless-cloud-notepad

推荐语：运行在 Cloudflare 上的云记事本，搭建简单，当做临时文本中转挺方便，并且支持 Markdown 语法，支持加密。

**Comment by zhuima** [comment]
👍酷，这个可以用作为临时收藏夹，ps:可以提个pr上来

**Comment by tszlznl** [comment]
> 👍酷，这个可以用作为临时收藏夹，ps:可以提个pr上来 我今天给你这个工具推荐一下

没提过 Pull requests，不知道是不是这样做，有问题你就帮忙处理一下吧。

**Comment by zhuima** [comment]
今天发了你的仓库，一万多阅读量，应该能给你增加些star
