### ISSUE TITLE
微信群超200人了，扫码进不去了，苦苦

### ISSUE THREAD

**Issue by behinder85** [zhuima/awesome-cloudflare#22]

**Comment by bugtrap-codeor** [comment]
俺也一样

**Comment by yray680** [comment]
希望能开二群

**Comment by CodeFarmerier** [comment]
俺也一样

**Comment by zhuima** [comment]
![image](https://github.com/zhuima/awesome-cloudflare/assets/5243524/c39cb92c-e5c5-4a73-a50d-b3a3db07dafc)

新的码，已经加过群的不要重复加了

**Comment by JSjump** [comment]
> ![image](https://private-user-images.githubusercontent.com/5243524/339049054-c39cb92c-e5c5-4a73-a50d-b3a3db07dafc.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODg5NTksIm5iZiI6MTcxODg4ODY1OSwicGF0aCI6Ii81MjQzNTI0LzMzOTA0OTA1NC1jMzljYjkyYy1lNWM1LTRhNzMtYTUwZC1iM2EzZGIwN2RhZmMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDEzMDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMjJkZTczMDRjYzIzOWU4NWQ5ZmYwYzAxZDFkYjRiNTY2MmRjMzJlNzgzN2Y2OTQ0OTM4OTY4NjAyMjM3YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eX0oHzPKyZLXazmqRh8qm9g9cun_wCnyxORwTcl2o9o)
> 
> 新的码，已经加过群的不要重复加了

大佬你好。方便更新入群二维码吗？过期了

**Comment by RabbitSudo** [comment]
过期了

**Comment by zhuima** [comment]
已更新

**Comment by zhuima** [comment]
精力有限，后续不再维护微信群了，想聊的可以加这个群组 [一个群](https://t.me/indiehackertools)
