### ISSUE TITLE
自荐，在gh-proxy的基础上探索了一下， 解决github脚本里面访问github资源的问题

### ISSUE THREAD

**Issue by crazypeace** [zhuima/awesome-cloudflare#23]
项目：
https://github.com/crazypeace/gh-proxy

[增加支持 api.github.com](https://zelikk.blogspot.com/2023/03/github-proxy-api-github-com.html)

增加支持 git.io

做了工具页面, 方便使用 https://ghproxy.crazypeace.workers.dev/

演示视频 https://youtu.be/F9re4Tuy7BA

在 Cloudflare 的 worker 上自建 Github 代理 教程 https://zelikk.blogspot.com/2023/06/gh-proxy-worker.html

在 Replit 上自建 Github 代理 教程 https://zelikk.blogspot.com/2023/07/replit-gh-proxy.html

**Comment by zhuima** [comment]
看着很厉害，绑定一个自定义域名就更好了，cloudflare域名是被ban的

**Comment by crazypeace** [comment]
基本操作啦
https://ghproxy.lvedong.eu.org/
