### ISSUE TITLE
补充一点

### ISSUE THREAD

**Issue by RaySibay** [zhuima/awesome-cloudflare#28]
突然发现，文章列表中的博客 "使用 Cloudflare Worker 代理 Google 站点" ，原博使用的是我在[RaySibay/workers_proxy_for_Google](https://github.com/RaySibay/workers_proxy_for_Google) 这个项目中的代码，目前我自己还在用，后续有更新的话会放在这个仓库里。

**Comment by zhuima** [comment]
方便提个pr么？
