### ISSUE TITLE
求教 SharzyL/pastebin-worker 的详细部署教程。

### ISSUE THREAD

**Issue by happymy** [zhuima/awesome-cloudflare#47]
求教 SharzyL/pastebin-worker 的详细部署教程。

**Comment by zhuima** [comment]
https://github.com/SharzyL/pastebin-worker 仓库里这里写的有， 6步操作(**最重要的是里面的修改 wrangler.toml 这一步**)， 另外就是想问下你是不会编程么？
![image](https://github.com/user-attachments/assets/2704e3cd-9cc1-40ba-8b88-bd61fe0f1d43)

**Comment by happymy** [comment]
懂一点点，worker刚接触不久。这种cl的部署方式没试过。已经弄好了。
